## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('CAMsend', ['core'])
    module.source = [
        'CAM-send.cc',
        ]
    headers = bld(features='ns3header')
    headers.module = 'CAMsend'
    headers.source = [
        'CAM-send.h',
        ]

