## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('messageMgmnt', ['core')
    module.source = [
        'CAMmanagement.cc',
        ]
    headers = bld(features='ns3header')
    headers.module = 'messageMgmnt'
    headers.source = [
        'CAMmanagement.h',
        ]

